spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myactiviti?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    druid:
      max-active: 5
    username: root
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
  activiti:
    check-process-definitions: false
  main:
    allow-bean-definition-overriding: true

